blank_issues_enabled: false
contact_links:
  - name: Discussions & Questions
    url: https://github.com/orgs/APIForge-Organisation/discussions
    about: Ask questions or share ideas in our GitHub Discussions.
